### ISSUE TITLE
Publication sort order: default reverse chronological

### ISSUE THREAD

**Issue by lintool** [dsg-uwaterloo/publications#1]
By default, the publications should be sorted reverse chronological order, most recent first.

**Comment by lintool** [comment]
@michaelmior What's the secondary sort order within a year? Seems like alphabetical? Can you make it fully reverse chronological? I.e., within each year, Dec, Nov, ...

This way we make sure all the papers within a conference are together... e.g., all SIGIR, all SIGMOD, etc. This might need a bit of custom code and hacking, since we want all the SIGIR main conference papers together, and the workshop papers together, etc.

**Comment by michaelmior** [comment]
Yes, alphabetical. It should be possible to go by month when DBLP has the information otherwise by year. One question is whether papers without the month should be placed at the beginning or end of the year.

**Comment by michaelmior** [comment]
Actually, it turns out in the XML data that DBLP returns, the month is not included, so I'm not sure we can easily do this. Example data below:

```xml
<r>
  <article key="journals/tkde/MiorSAL17" mdate="2017-10-16">
    <author>Michael J. Mior</author>
    <author>Kenneth Salem</author>
    <author>Ashraf Aboulnaga</author>
    <author>Rui Liu</author>
    <title>NoSE: Schema Design for NoSQL Applications.</title>
    <pages>2275-2289</pages>
    <year>2017</year>
    <volume>29</volume>
    <journal>IEEE Trans. Knowl. Data Eng.</journal>
    <number>10</number>
    <ee>https://doi.org/10.1109/TKDE.2017.2722412</ee>
    <ee>
      http://doi.ieeecomputersociety.org/10.1109/TKDE.2017.2722412
    </ee>
    <url>db/journals/tkde/tkde29.html#MiorSAL17</url>
  </article>
</r>
```

**Comment by lintool** [comment]
Doesn't DBLP do within-year sorting correctly? If not, then use venue (e.g., conference or journal) as the secondary sort within year?

**Comment by michaelmior** [comment]
I think they do but only because they add articles when they are discovered so assuming all sources are updated and crawled at similar rates, things end up naturally in the right order even though they have to explicit ordering information. I'll try sorting by year, then venue, then author.
