### ISSUE TITLE
Who should be on list of authors?

### ISSUE THREAD

**Issue by lintool** [dsg-uwaterloo/publications#4]
Since students publish with faculty (i.e., their advisors) by default, should we include all students in the authors list? This has the effect of bringing in student publications prior to Waterloo, and continuing to bring in their publications after they've graduated (unless we've removed them from the list).

Thoughts?

**Comment by michaelmior** [comment]
Most, but not all publications are with an advisor. This would miss the occasional publication which doesn't include UW faculty. We could also include a range of years for each author if we only want publications from their time at UW. Faculty also come and go too.

**Comment by lintool** [comment]
Yes, but DSG should get credit for all my pubs at UMD 😄 

Okay, no problem keeping students on at this point, but yes, a year delimiter would make sense. Or we'll just claim all of Xu's future pubs at GA tech.

**Comment by michaelmior** [comment]
Anything else we need to do then if we have a year restriction?
