### ISSUE TITLE
Separate presentation and data layer

### ISSUE THREAD

**Issue by lintool** [dsg-uwaterloo/publications#5]
I propose to refactor the code to separate the presentation and data layers:

+ the data layer is the node crawling - the output should be JSON data files.
+ the presentation layer should be js code that takes in the JSON files and renders the actual bib entries.

This is a better design than the current one in which HTML is rendered directly... since it'll be such easier to add in dynamic elements, e.g., filtering.

**Comment by michaelmior** [comment]
This already is separated, just not in the way you expected. I'm using the [Citation Style Language](http://citationstyles.org/) which is a widely used format for defining citation styles. I started with IEEE style and [customized the format](https://github.com/dsg-uwaterloo/publications/blob/master/dsg.csl). I did also pull most of the HTML out of the script and into a [separate template](https://github.com/dsg-uwaterloo/publications/blob/master/citations.mustache).

**Comment by lintool** [comment]
Can we use ACM format? I think that aligns better with most of the papers we write?

**Comment by lintool** [comment]
One more thing:

> Ziawasch Abedjan, Lukasz Golab, and Felix Naumann, “Data Profiling: A Tutorial.,” in SIGMOD Conference, 2017, pp. 1747–1751.

We got extra punctuation in title, before the close quote...

**Comment by michaelmior** [comment]
Sure, I can switch to ACM format. I tried that at first and I can't recall why, but I had a reason for switching. I can make that work. I think the extra punctuation there may be part of the formatting that we can just remove. Otherwise, it may be more challenging since we don't neccessary always want to remove trailing punctuation.  (e.g., if a title ends with an acronym where periods are used)

**Comment by michaelmior** [comment]
So the periods *are* included in the titles returned by DBLP. If we're willing to accept the possibility that sometimes they should still be there, I can just strip them off.

**Comment by michaelmior** [comment]
Actually, switched to ACM style and this issue goes away since a comma no longer follows and duplicate periods are not used. If you're happy with the version currently posted, this can be closed.
