### ISSUE TITLE
Add ability to blacklist individual entries

### ISSUE THREAD

**Issue by lintool** [dsg-uwaterloo/publications#7]
We should add the ability to suppress individual entries (i.e., a blacklist). DBLP isn't perfect:

+ In some cases, multiple profiles get created for an individual author... which is annoying but fine - we just crawl multiple profiles.
+ In other cases, spurious papers get add to a profile (i.e., papers that I didn't write). 

We need a blacklist for the second case.

**Comment by michaelmior** [comment]
Sounds good. DBLP has a key associated with each entry which you can see on the website by hovering over the export button. I'll just add a separate file that will contain a list of keys to exclude.

**Comment by michaelmior** [comment]
Any examples I can add into the blacklist so I just don't commit an empty file? I want to make it obvious what should go in there.

**Comment by lintool** [comment]
As an example, these are not mine: 
http://dblp.org/rec/conf/isbi/BejnordiLGMGSKL17
http://dblp.org/rec/journals/corr/BejnordiLGMGSKL17
