### ISSUE TITLE
Some bibtex entries missing titles

### ISSUE THREAD

**Issue by lintool** [dsg-uwaterloo/publications#9]
For example, we see:

```
@inproceedings{Toman_Weddell_2015b, DOI={http://ceur-ws.org/Vol-1350/paper-36.pdf}, booktitle={Description Logics}, author={Toman, David and Weddell, Grant}, year={2015}}
```

Any ideas why?

**Comment by michaelmior** [comment]
I notice that the title DBLP returns has some markup in it (one acronym is italicized). I'm guessing that might have something to do with it. I'll take a look now.

**Comment by michaelmior** [comment]
Pretty ugly hack, but gets the job done for now.
